# Generated by Django 3.0.7 on 2020-07-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200727_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
