# Generated by Django 3.0.7 on 2020-07-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200727_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='des',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='dev',
            field=models.BooleanField(default=False),
        ),
    ]
